Trader_Dayz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('general.urls')),
]

general/urls.py
from django.urls import path
from .views import *

app_name = 'general'

urlpatterns = [
    path('', main_cover, name='main_page'),
    path('table/', tabel_view, name='table'),
    path('import/', trader_txt_import, name='import'),
]

general/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Trader(models.Model):
    name = models.TextField(verbose_name='Название трейдера')
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.TextField(verbose_name='Категория товара')
    attach_to_trader = models.ForeignKey(Trader, on_delete=models.DO_NOTHING, verbose_name='Относится к трейдеру')
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class Item(models.Model):
    CHOICES = (
        ("*", "Максимум"),
        ("V", "Транспортное средство"),
        ("VNK", "Транспортное средство без ключа"),
        ("M", "Магазин для патронов"),
        ("W", "Оружие"),
        ("S", "Стейк из мяса"),
        ("K", "Дубликат ключа"),

    )
    class_name = models.TextField(verbose_name='Наименование товара')
    quantity = models.CharField(
        max_length=7,
        choices=CHOICES,
        default='*'
    )
    buyvalue = models.IntegerField(verbose_name="Покупка")
    sellvalue = models.IntegerField(verbose_name="Продажа")
    attach_to_category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, verbose_name='Относится к категории')
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.class_name

general/views.py
import re

from django.shortcuts import render
from .models import *


def main_cover(request):
    context = {
        'name': 'some_text',
    }
    return render(request, 'pages/startpage.html', context)


def tabel_view(request):
    data = Item.objects.all()
    context = {
        'items': data
    }
    return render(request, 'pages/dashboard.html', context)


def trader_txt_import(request):
    traders = []
    categories = []
    items = []
    id_category = -1,
    with open('D:\\Python_Projects\\Trader_Dayz\\general\\tradef.txt', 'r', encoding='utf-8') as config:
        for i in config:

            values = i.strip()
            if values.startswith('<Trader>'):
                pass
                Trader.objects.create(name=values, owner_id=request.user.id)
                id_trader = Trader.objects.filter(name=values,owner_id=request.user.id).order_by('-id')[0].id
            elif values.startswith('<Category>'):
                pass
                Category.objects.create(name=values, attach_to_trader_id=id_trader, owner_id=request.user.id)
                id_category = Category.objects.filter(name=values, owner_id=request.user.id).order_by('-id')[0].id
            elif values.istitle():

                lst = values.replace('\t', '').split(',')
                print(lst)
                print(id_category)
                if len(lst) == 4:
                    Item.objects.create(class_name=lst[0], quantity=lst[1], buyvalue=int(lst[2]), sellvalue=int(lst[3]),
                                        owner_id=request.user.id, attach_to_category_id=id_category)

        print(traders)
    context = {
        'text': 'txt'
    }
    return render(request, 'pages/dashboard.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="generator" content="Hugo 0.88.1">
    <title>DayZ Trader Generator</title>





    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">





    <!-- Custom styles for this template -->

  </head>

    {% block content %}
    {% endblock content %}
      <footer class="mt-auto text-white-50">
    <p>Дополнительное приложение для <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=1590841260" class="text-white">DayZ Trader</a>, by <a href="https://steamcommunity.com/id/dr_j0nes" class="text-white">dr_j0nes</a>.</p>
  </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>

  </body>
</html>

templates/pages/dashboard.html
{% extends 'base.html' %}
{% load static %}

  {% block content %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}dashboard.css" rel="stylesheet">

  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url 'general:main_page' %}">DayZ Trader</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>

        </ul>



      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>

        </div>
      </div>



      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Class Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Buy Value</th>
                <th scope="col">Sell Value</th>
                <th scope="col">Category</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ item.class_name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.buyvalue}}</td>
                    <td>{{ item.sellvalue}}</td>
                    <td>{{ item.attach_to_category}}</td>
                </tr>
            {% endfor %}
        </tbody>
        </table>


      </div>
    </main>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
  </body>
{% endblock content %}

templates/pages/startpage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
      <body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">DTG</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link " aria-current="page" href="{% url 'general:main_page' %}">Главная</a>
        <a class="nav-link" href="{% url 'general:table' %}">Генератор</a>
        <a class="nav-link" href="#">Контакты</a>
      </nav>
    </div>
  </header>
  <main class="px-3">
    <h1>Генератор конфигураций Trader</h1>
    <p class="lead">Создайте свою конфигурацию популярного мода DayZ "Trader". Назначайте цены, добавляйте товары, создавайте новых торговцев.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Перейти к генератору</a>
    </p>
  </main>
{% endblock content %}

templates/pages/table.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
   <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Class Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Buy Value</th>
      <th scope="col">Sell Value</th>
      <th scope="col">Category</th>
    </tr>
  </thead>
  <tbody>
  {% for item in items %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.class_name }}</td>
      <td>{{ item.quantity }}</td>
      <td>{{ item.buyvalue}}</td>
      <td>{{ item.sellvalue}}</td>
      <td>{{ item.category}}</td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock content %}